server:
  port: 4000

spring:
  application:
    name: homework
  datasource:
    url: jdbc:postgresql://localhost:5432/homework
    username: postgres
    password: admin
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    locations: classpath:db/migration,classpath:dev/db/migration