server:
  port: 4010

spring:
  application:
    name: homework
  datasource:
    url: jdbc:postgresql://localhost:5432/qa_homework
    username: postgres
    password: admin
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format-sql: true
    hibernate:
      ddl-auto: update
  jackson:
    serialization:
      fail-on-empty-beans: false